### ISSUE TITLE
Sakura 3.8.1 dependencies

### ISSUE THREAD

**Issue by brucehankins** [brucehankins/Solus-Packaging#2]
Sakura 3.8.1 requires pango version >= 39
Currently Solus Budige includes version: 1.48.3, release: 38

Will wait for Solus devs to update pango to release 39.

**Comment by algent-al** [comment]
That is because you are building packages against unstable repository in solbuild and using stable repo for your system.

**Comment by algent-al** [comment]
One solution is to switch to Unstable repo and keep an eye to #Solus-Dev IRC channel, to know when is not safe to update.

**Comment by brucehankins** [comment]
Well that would be why....to build against shannon, it would be sudo solbuild build package.yml -p main-x86_64?

**Comment by algent-al** [comment]
Yes, you can build against shannon, but I can't confrim that command since I never did before.

**Comment by brucehankins** [comment]
With upgrade on 04/30 and push to Gnome Stack 40, Sakura now installs correctly against Shannon repos.
